### PR TITLE
fix: throw error if provider is initialized while it is alreary loading

### LINKED ISSUE #26: Validation is run twice
image

This output is confusing because you cannot tell that adonis-apollo ran the validation of the schema twice and only the last error is valid. This happens not only when starting the server for the first time, but also when restarting the server after source files changed.

I don't know adonis well enough to understand why this code seems to be running before the compilation finished. Is this the expected behavior?

### PR DESCRIPTION
**Pull request by stropitek**
Closes #26 

image

Stack trace clearly shows the import line which is nice

### CODE REVIEW

File: providers/ApolloProvider.ts [hunk 1]
```diff
@@ -12,12 +12,17 @@ import { ApolloConfig } from '@ioc:Apollo/Config';
...
+  protected loading = false;
   public static needsApplication = true;
-
   public constructor(protected app: ApplicationContract) {}
 
   public register(): void {
     this.app.container.singleton('Apollo/Server', () => {
+      if (this.loading) {
+        throw new Error(
+          'ApolloProvider was called during its initialization. Using this provider in resolvers is not supported.',
```
Comment (targos) [inline providers/ApolloProvider.ts:23]:
```suggestion
          'ApolloProvider was called during its initialization. To use this provider in resolvers, use dynamic `import()`.',
```
